run_config:
  name: apartment-rentals
  author: AWS-MLOps-Team
  version: default
  description: Predict apartment rental prices.
  dependencies: requirements.txt
  data_source: https://archive.ics.uci.edu/static/public/555/apartment+for+rent+classified.zip
  clean_data_key: data/toy_data.csv
  output: results
  
get_data: 
  output_path: data
  
# generate_features:

train_model:
  target_var: price_display
  test_size: 0.2
  seed: 11318
  k_cv: 5
  initial_features:
    - bedrooms
    - bathrooms
    - square_feet
  rf_params:
    n_estimators: [10, 50, 100, 200]
    max_depth: [5, 10, 15]


score_model: 
  target_var: price_display
  initial_features:
    - bedrooms
    - bathrooms
    - square_feet

aws:
   bucket_name: aws-mlops-project
   prefix: modeling/