run_config:
  name: apartment-rentals
  author: AWS-MLOps-Team
  version: default
  description: Predict apartment rental prices.
  dependencies: requirements.txt
  data_source: https://archive.ics.uci.edu/static/public/555/apartment+for+rent+classified.zip
  output: runs
get_data: 
  output_path: data
# generate_features:
# train_model:
#   split_data:
#     test_size: 
#     random_state:
#   choose_features:
#     features_to_use: 
#   get_target:
#     target_feature: 
#   model_training:
#     n_estimators: 
#     max_depth: 
# score_model:
#   choose_features:
#     features_to_use: 
#   get_target:
#     target_feature: 
#   score_type: 
#     probability: 
#     label: 
#     truth: 
# evaluate_performance:
#   score_type: 
#     probability: 
#     label: 
#     truth: 
#   metric_type:
#     r2_score: 
#     mse: 
# aws:
#   upload: True
#   bucket_name: smv7369-clouds-hw2
#   region_name: us-east-2