run_config:
  name: apartment-rentals
  author: AWS-MLOps-Team
  version: default
  description: Predict apartment rental prices.
  dependencies: requirements.txt
  data_source: https://archive.ics.uci.edu/static/public/555/apartment+for+rent+classified.zip
  clean_train_key: data/clean/data_cleaned_train.csv
  clean_test_key: data/clean/data_cleaned_test.csv
  output: results

train_model:
  target_var: price
  k_cv: 5
  initial_features:
    - n_amenities
    - bathrooms
    - bedrooms
    - square_feet
    - dogs_allowed
    - cats_allowed
    - fee
    - has_photo
  rf_params:
    n_estimators: [10, 50, 100]
    max_depth: [5, 10]

score_model: 
  target_var: price

aws:
   bucket_name: aws-mlops-project
   prefix: modeling_artifacts